name: Daily copy of a web file in a repository
# This workflow is triggered on pushes to the repository daily at 07:00
on:
  schedule:
    - cron: '0/10 * * * *'

jobs:
  timeprint:
    name: TimePrintJob
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello World
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: TimePrintStep
        run: echo 'The time was ${{steps.hello.outputs.time}}.'
